import { AlpacaExecution, Recommendation } from '@/types/database'
import ActionList from './ActionList'
import AgentBreakdown from './AgentBreakdown'
import AlpacaExecuteButton from './AlpacaExecuteButton'
import AlpacaResultsPanel from './AlpacaResultsPanel'

interface Props {
  recommendation: Recommendation
  recommendationId: string
  isLatest: boolean
  hasCredentials: boolean
  isPaper: boolean
  execution: AlpacaExecution | null
}

const DISCLAIMER_TEXT =
  'This analysis is generated by AI and is for informational purposes only. ' +
  'It does not constitute regulated financial advice. ' +
  'Always consult a qualified financial adviser before making investment decisions.'

export default function RecommendationDetail({
  recommendation,
  recommendationId,
  isLatest,
  hasCredentials,
  isPaper,
  execution,
}: Props) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
      {/* Disclaimer banner */}
      <div
        style={{
          background: '#fef9c3',
          border: '1px solid #ca8a04',
          borderRadius: 8,
          padding: '12px 16px',
          marginBottom: 24,
          color: '#92400e',
          fontSize: 14,
          lineHeight: 1.5,
          fontFamily: 'var(--sans)',
        }}
      >
        {DISCLAIMER_TEXT}
      </div>

      {/* Summary */}
      <p
        style={{
          fontSize: 15,
          color: 'var(--ink-2)',
          lineHeight: 1.7,
          marginBottom: 32,
          fontFamily: 'var(--sans)',
        }}
      >
        {recommendation.summary_text ?? 'Summary not available.'}
      </p>

      {/* Recommended Actions */}
      <section style={{ marginBottom: 32 }}>
        <h2
          style={{
            fontFamily: 'var(--display)',
            fontWeight: 700,
            fontSize: 20,
            color: 'var(--ink)',
            marginBottom: 16,
          }}
        >
          Recommended Actions
        </h2>
        <div style={{ marginBottom: 16 }}>
          <AlpacaExecuteButton
            recommendationId={recommendationId}
            hasCredentials={hasCredentials}
            isPaper={isPaper}
            isLatest={isLatest}
            alreadyExecuted={execution !== null}
            executedAt={execution?.executed_at ?? null}
          />
          {execution !== null && (
            <AlpacaResultsPanel execution={execution} />
          )}
        </div>
        <ActionList actionList={recommendation.action_list ?? []} />
      </section>

      {/* Agent Analysis */}
      <section style={{ marginBottom: 32 }}>
        <h2
          style={{
            fontFamily: 'var(--display)',
            fontWeight: 700,
            fontSize: 20,
            color: 'var(--ink)',
            marginBottom: 16,
          }}
        >
          Agent Analysis
        </h2>
        <AgentBreakdown agentOutputs={recommendation.agent_outputs ?? {}} />
      </section>

      {/* Conflict notes — only when truthy */}
      {recommendation.conflict_notes && (
        <section style={{ marginBottom: 32 }}>
          <h2
            style={{
              fontFamily: 'var(--display)',
              fontWeight: 700,
              fontSize: 20,
              color: 'var(--ink)',
              marginBottom: 16,
            }}
          >
            Agent Disagreements
          </h2>
          <p
            style={{
              fontSize: 14,
              color: 'var(--ink-2)',
              lineHeight: 1.6,
              fontFamily: 'var(--sans)',
            }}
          >
            {recommendation.conflict_notes}
          </p>
        </section>
      )}
    </div>
  )
}
